// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQFhbeMxxqkC__lWN4fMh3_CFaE58unVk',
    appId: '1:1038722759810:web:2680b3472ef6eaf702489b',
    messagingSenderId: '1038722759810',
    projectId: 'yumshare-e7299',
    authDomain: 'yumshare-e7299.firebaseapp.com',
    storageBucket: 'yumshare-e7299.firebasestorage.app',
    measurementId: 'G-Z3R738W5Q4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwrtKH3Dq-esyIvQOgjd3NUIHyHcP4r6k',
    appId: '1:1038722759810:android:bf6f3bb69279ae5102489b',
    messagingSenderId: '1038722759810',
    projectId: 'yumshare-e7299',
    storageBucket: 'yumshare-e7299.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN6mLjKZ9BHVNQoQAtKXsO2jnZyf_lP6c',
    appId: '1:1038722759810:ios:a3d6f7bf3b72d2f902489b',
    messagingSenderId: '1038722759810',
    projectId: 'yumshare-e7299',
    storageBucket: 'yumshare-e7299.firebasestorage.app',
    iosBundleId: 'com.example.yumshare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN6mLjKZ9BHVNQoQAtKXsO2jnZyf_lP6c',
    appId: '1:1038722759810:ios:a3d6f7bf3b72d2f902489b',
    messagingSenderId: '1038722759810',
    projectId: 'yumshare-e7299',
    storageBucket: 'yumshare-e7299.firebasestorage.app',
    iosBundleId: 'com.example.yumshare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQFhbeMxxqkC__lWN4fMh3_CFaE58unVk',
    appId: '1:1038722759810:web:e70efb90d495acba02489b',
    messagingSenderId: '1038722759810',
    projectId: 'yumshare-e7299',
    authDomain: 'yumshare-e7299.firebaseapp.com',
    storageBucket: 'yumshare-e7299.firebasestorage.app',
    measurementId: 'G-TTBSSWEKWK',
  );
}
